### ISSUE TITLE
ch4

### ISSUE THREAD

**Issue by aishahmohamed98** [PriceLab/STP#5]
@paul-shannon hey paul, i've uploaded my chapter 4 challenges in both r and python onto the repo. would you mind checking for errors, comment and advise!!

-Aishah

**Comment by paul-shannon** [comment]
will do!   before I leave today.

**Comment by paul-shannon** [comment]
in challenges.py:

always good to give names to variables and functions which are meaningful and clarifying.   for the reader!   so rather than ````divide````  how about ````divideBy2````?   And ````multiplyBy4````, `toFloat````

In your #2 comments in challenges.py, "2 functions" are mentioned, with the result of the first passed to the second.  not sure you did that....  How about these two approaches?
````
y = divideBy2(18)
print(multiplyBy4(y))
````
or better yet

````
print(multiplyBy4(divideBy2(18)))
````

**Comment by aishahmohamed98** [comment]
ive just uploaded my edits paul!
